if(TARGET WrapAssimp::WrapAssimp)
  set(WrapAssimp_FOUND TRUE)
  return()
endif()

find_package(assimp ${WrapAssimp_FIND_VERSION} CONFIG QUIET)
if (assimp_FOUND AND TARGET assimp::assimp)
  add_library(WrapAssimp::WrapAssimp INTERFACE IMPORTED)
  target_link_libraries(WrapAssimp::WrapAssimp INTERFACE assimp::assimp)
  set(WrapAssimp_FOUND TRUE)
elseif(assimp_FOUND AND assimp_LIBRARIES AND assimp_INCLUDE_DIRS)
  add_library(WrapAssimp::WrapAssimp INTERFACE IMPORTED)
  target_link_libraries(WrapAssimp::WrapAssimp INTERFACE ${assimp_LIBRARIES})
  target_include_directories(WrapAssimp::WrapAssimp INTERFACE ${assimp_INCLUDE_DIRS})
  set(WrapAssimp_FOUND TRUE)
endif()
